### ISSUE TITLE
76. Minimum Window Substring - LeetCode Hard Solution 

### ISSUE THREAD

**Issue by saniaahmad6** [SoumyadeepMukherjee/Advanced-DSA#92]
Hello @SoumyadeepMukherjee 

Please assign this issue to me:

1. O(n) Time complexity
2. O(n) Space complexity
3. Two pointer and hash-map approach

**Comment by saniaahmad6** [comment]
Hello,
This repository is shown excluded from HacktoberFest 2022. So, the accepted
merge request is not being included in the overall count.

Could you please look into it?

Thanks!

**Comment by SoumyadeepMukherjee** [comment]
Yeah even I myself was wondering what caused it to be excluded as many of my friends who contributed also had the same problem! I guess it was because of the name "Hacktoberfest2022" in the repo name which I didn't know. However I changed it, still it shows excluded, so I guess it will not be counted.

Sorry for the inconvenience though!
